export const categories = [
  {
    title: "Electronics",
    items: [
      "Mobile Phones",
      "Laptops",
      "Cameras",
      "Headphones",
      "Smartwatches",
      "Gaming Consoles",
      "Accessories",
    ],
  },
  {
    title: "Clothing",
    items: [
      "Men's Clothing",
      "Women's Clothing",
      "Kids' Clothing",
      "Footwear",
      "Winter Wear",
      "Activewear",
      "Accessories",
    ],
  },
  {
    title: "Home & Kitchen",
    items: [
      "Furniture",
      "Kitchen Appliances",
      "Cookware",
      "Home Decor",
      "Bedding",
      "Storage Solutions",
      "Cleaning Supplies",
    ],
  },
  {
    title: "Beauty",
    items: [
      "Makeup",
      "Skincare",
      "Hair Care",
      "Perfumes",
      "Bath & Body",
      "Nail Care",
      "Tools & Accessories",
    ],
  },
  {
    title: "Health",
    items: [
      "Supplements",
      "Fitness Equipment",
      "Healthcare Devices",
      "Vitamins",
      "Personal Care",
      "First Aid",
      "Hygiene Products",
    ],
  },
  {
    title: "Books",
    items: [
      "Fiction",
      "Non-Fiction",
      "Children's Books",
      "Educational",
      "Comics",
      "Biographies",
      "Self-Help",
    ],
  },
  {
    title: "Toys",
    items: [
      "Action Figures",
      "Puzzles",
      "Educational Toys",
      "Dolls",
      "Outdoor Toys",
      "Board Games",
      "RC Toys",
    ],
  },
  {
    title: "Sports",
    items: [
      "Cricket Gear",
      "Football Equipment",
      "Cycling",
      "Gym Essentials",
      "Outdoor Sports",
      "Swimming Gear",
      "Tennis Accessories",
    ],
  },
  {
    title: "Automotive",
    items: [
      "Car Accessories",
      "Bike Accessories",
      "Oils & Lubricants",
      "Car Care",
      "Tools",
      "Tires",
      "Navigation Systems",
    ],
  },
];
